-- Generated by scripts/dump-catalog-to-sql.ts
-- Source: ./prisma/dev.sqlite
-- Generated at: 2026-05-20T20:46:02.677Z
-- Safe to re-apply: every INSERT uses ON CONFLICT (id) DO NOTHING

BEGIN;

-- Supplier
INSERT INTO "Supplier" (id, name, "createdAt") VALUES ('cmfcobwuq00002mtv9aur8pvg', 'DSL Global', '2025-09-09T14:56:45.842Z'::timestamp) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Supplier" (id, name, "createdAt") VALUES ('cmfcobwur00052mtv1jdb4aqb', 'Maiavie', '2025-09-09T14:56:45.842Z'::timestamp) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Supplier" (id, name, "createdAt") VALUES ('cmfcobwv700092mtvv513k8aj', 'Ingredient Superfood', '2025-09-09T14:56:45.860Z'::timestamp) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Supplier" (id, name, "createdAt") VALUES ('cmfcobwv9000a2mtvylnnfmxl', 'Nakosport', '2025-09-09T14:56:45.861Z'::timestamp) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Supplier" (id, name, "createdAt") VALUES ('cmfcobwur00042mtvl2g55zud', 'Inlead', '2025-09-09T14:56:45.842Z'::timestamp) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Supplier" (id, name, "createdAt") VALUES ('cmfcobwvd000c2mtv7to6ugzf', 'Nutrimea', '2025-09-09T14:56:45.865Z'::timestamp) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Supplier" (id, name, "createdAt") VALUES ('cmfcobwvf000d2mtveshrcpgy', 'Nutrimeo', '2025-09-09T14:56:45.867Z'::timestamp) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Supplier" (id, name, "createdAt") VALUES ('cmfcobwvh000e2mtvemswoji7', 'Ostrovit', '2025-09-09T14:56:45.869Z'::timestamp) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Supplier" (id, name, "createdAt") VALUES ('cmfcobwvi000f2mtv18uo541e', 'Pb Wholesale', '2025-09-09T14:56:45.871Z'::timestamp) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Supplier" (id, name, "createdAt") VALUES ('cmfcobwvk000g2mtvts9t1erp', 'Powerbody', '2025-09-09T14:56:45.873Z'::timestamp) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Supplier" (id, name, "createdAt") VALUES ('cmfcobwvm000h2mtv8yi3v05p', 'Pro Supply', '2025-09-09T14:56:45.875Z'::timestamp) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Supplier" (id, name, "createdAt") VALUES ('cmfcobwur00062mtv0vimiur3', 'Addict', '2025-09-09T14:56:45.842Z'::timestamp) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Supplier" (id, name, "createdAt") VALUES ('cmfcobwvp000j2mtv6uq6xz6i', 'Rabeko', '2025-09-09T14:56:45.877Z'::timestamp) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Supplier" (id, name, "createdAt") VALUES ('cmfcobwvq000k2mtv45yi81vs', 'Shaker store', '2025-09-09T14:56:45.879Z'::timestamp) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Supplier" (id, name, "createdAt") VALUES ('cmfcobwvs000l2mtv7q8gs2sq', 'Swanson', '2025-09-09T14:56:45.880Z'::timestamp) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Supplier" (id, name, "createdAt") VALUES ('cmfcobwvt000m2mtvm6oets0k', 'Yamamoto', '2025-09-09T14:56:45.881Z'::timestamp) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Supplier" (id, name, "createdAt") VALUES ('cmfcobwvu000n2mtvip9wkc0c', 'Labz Nutrition', '2025-09-09T14:56:45.882Z'::timestamp) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Supplier" (id, name, "createdAt") VALUES ('cmfcobwvv000o2mtvy5tfb3v3', 'Liot', '2025-09-09T14:56:45.883Z'::timestamp) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Supplier" (id, name, "createdAt") VALUES ('cmfcobwvw000p2mtvp9k1jspj', 'Max protein', '2025-09-09T14:56:45.885Z'::timestamp) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Supplier" (id, name, "createdAt") VALUES ('cmfcobwus00072mtvl76q3ara', 'Io genix', '2025-09-09T14:56:45.842Z'::timestamp) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Supplier" (id, name, "createdAt") VALUES ('cmfcobwvo000i2mtv9jmixqn1', 'Prolife', '2025-09-09T14:56:45.876Z'::timestamp) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Supplier" (id, name, "createdAt") VALUES ('cmfcobwvb000b2mtvhxgict0x', 'Novoma', '2025-09-09T14:56:45.863Z'::timestamp) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Supplier" (id, name, "createdAt") VALUES ('cmfcobwur00022mtvd709apmu', 'Bolero', '2025-09-09T14:56:45.842Z'::timestamp) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Supplier" (id, name, "createdAt") VALUES ('cmfcobwv400082mtv2owlx175', 'Life pro', '2025-09-09T14:56:45.857Z'::timestamp) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Supplier" (id, name, "createdAt") VALUES ('cmfcobwuq00012mtvri2j58d9', 'Dynveo', '2025-09-09T14:56:45.842Z'::timestamp) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Supplier" (id, name, "createdAt") VALUES ('cmfcobwur00032mtvshsl8f48', 'Buchteiner', '2025-09-09T14:56:45.842Z'::timestamp) ON CONFLICT (id) DO NOTHING;

-- Product
INSERT INTO "Product" (id, name, "skuFwn", "createdAt") VALUES ('cmfcobwz3000t2mtvvg3b2ubu', 'Energy Drink Original', 'ENERGY-ORIG', '2025-09-09T14:56:45.999Z'::timestamp) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Product" (id, name, "skuFwn", "createdAt") VALUES ('cmfcobwz3000r2mtvku6r4ebb', 'Ice Tea Peach', 'ICE-PEACH', '2025-09-09T14:56:45.999Z'::timestamp) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Product" (id, name, "skuFwn", "createdAt") VALUES ('cmfcobwz3000v2mtvwjn9b90z', 'Orange Juice 1L', 'JUICE-ORANGE', '2025-09-09T14:56:45.999Z'::timestamp) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Product" (id, name, "skuFwn", "createdAt") VALUES ('cmfcobwz3000u2mtvtyfa07os', 'Sparkling Water Lemon', 'SPARK-LEMON', '2025-09-09T14:56:45.999Z'::timestamp) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Product" (id, name, "skuFwn", "createdAt") VALUES ('cmfcobwz3000s2mtvpx4f8n3t', 'Mineral Water 500ml', 'WATER-500', '2025-09-09T14:56:45.999Z'::timestamp) ON CONFLICT (id) DO NOTHING;
INSERT INTO "Product" (id, name, "skuFwn", "createdAt") VALUES ('cmfcobwz3000q2mtv4xu71fvr', 'Ice Tea Lemon', 'ICE-LEMON', '2025-09-09T14:56:45.999Z'::timestamp) ON CONFLICT (id) DO NOTHING;

-- SupplierSKU
INSERT INTO "SupplierSKU" (id, "productId", sku, brand) VALUES ('cmfcobx0x00112mtvek3spvwd', 'cmfcobwz3000q2mtv4xu71fvr', 'BOL-ICE-LEM-001', 'Bolero') ON CONFLICT (id) DO NOTHING;
INSERT INTO "SupplierSKU" (id, "productId", sku, brand) VALUES ('cmfcobx0x00152mtv1a0cvtrg', 'cmfcobwz3000t2mtvvg3b2ubu', 'MAX-ENG-ORIG-001', 'Max protein') ON CONFLICT (id) DO NOTHING;
INSERT INTO "SupplierSKU" (id, "productId", sku, brand) VALUES ('cmfcobx0x00172mtv0pe4ywpy', 'cmfcobwz3000v2mtvwjn9b90z', 'NUT-JUICE-ORG-001', 'Nutrimea') ON CONFLICT (id) DO NOTHING;
INSERT INTO "SupplierSKU" (id, "productId", sku, brand) VALUES ('cmfcobx0x00122mtvo2crnav3', 'cmfcobwz3000s2mtvpx4f8n3t', 'SWA-WAT-500-001', 'Swanson') ON CONFLICT (id) DO NOTHING;
INSERT INTO "SupplierSKU" (id, "productId", sku, brand) VALUES ('cmfcobx0x00102mtvybk3lnyy', 'cmfcobwz3000r2mtvku6r4ebb', 'BOL-ICE-PEA-002', 'Bolero') ON CONFLICT (id) DO NOTHING;
INSERT INTO "SupplierSKU" (id, "productId", sku, brand) VALUES ('cmfcobx0x00162mtv3aey3ilu', 'cmfcobwz3000u2mtvtyfa07os', 'DSL-SPARK-LEM-001', 'DSL Global') ON CONFLICT (id) DO NOTHING;

COMMIT;
