// Reads Supplier / Product / SupplierSKU from a local SQLite snapshot
// (prisma/dev.sqlite by default) and emits a Postgres-flavoured SQL file
// that can be applied with `prisma db execute --file …` on the target
// database. The generated file uses ON CONFLICT (id) DO NOTHING so it
// is safe to apply repeatedly.
//
// Usage (run locally, doesn't touch any database):
//   npx tsx scripts/dump-catalog-to-sql.ts
//   # writes prisma/seeds/initial-catalog.sql
//
// Then commit the generated SQL — Coolify deploys will pick it up and
// dbsetup.js applies it after `prisma migrate deploy`.

import { execFileSync } from "node:child_process";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";

const SQLITE_PATH = process.env.SQLITE_PATH ?? "./prisma/dev.sqlite";
const OUT_PATH = process.env.OUT_PATH ?? "./prisma/seeds/initial-catalog.sql";

if (!existsSync(SQLITE_PATH)) {
  console.error(`✖ SQLite file not found at ${SQLITE_PATH}`);
  process.exit(1);
}

type SupplierRow = { id: string; name: string; createdAt: string };
type ProductRow = { id: string; name: string; skuFwn: string; createdAt: string };
type SupplierSKURow = {
  id: string;
  productId: string;
  sku: string;
  brand: string | null;
};

function readJson<T>(query: string): T[] {
  const out = execFileSync("sqlite3", [SQLITE_PATH, "-json", query], {
    encoding: "utf8",
    maxBuffer: 64 * 1024 * 1024,
  });
  return out.trim() ? (JSON.parse(out) as T[]) : [];
}

// Postgres string escaping: double single-quotes. NULL stays unquoted.
function sqlString(v: string | null | undefined): string {
  if (v === null || v === undefined) return "NULL";
  return `'${v.replace(/'/g, "''")}'`;
}

// Prisma+SQLite stores DateTime as INTEGER (ms since epoch), exported as a
// numeric string. Convert to ISO so Postgres TIMESTAMP can parse it.
function sqlTimestamp(v: string | number | null | undefined): string {
  if (v === null || v === undefined || v === "") return "CURRENT_TIMESTAMP";
  const ms = typeof v === "number" ? v : parseInt(String(v), 10);
  if (Number.isFinite(ms)) {
    return `'${new Date(ms).toISOString()}'::timestamp`;
  }
  // Fallback: assume it's already an ISO string
  return `'${v}'::timestamp`;
}

const suppliers = readJson<SupplierRow>("SELECT id, name, createdAt FROM Supplier");
const products = readJson<ProductRow>("SELECT id, name, skuFwn, createdAt FROM Product");
const skus = readJson<SupplierSKURow>(
  'SELECT id, productId, sku, brand FROM "SupplierSKU"'
);

console.log(
  `📦 Source rows: ${suppliers.length} suppliers, ${products.length} products, ${skus.length} SKUs`
);

const lines: string[] = [];
lines.push("-- Generated by scripts/dump-catalog-to-sql.ts");
lines.push(`-- Source: ${SQLITE_PATH}`);
lines.push(`-- Generated at: ${new Date().toISOString()}`);
lines.push("-- Safe to re-apply: every INSERT uses ON CONFLICT (id) DO NOTHING");
lines.push("");

lines.push("BEGIN;");
lines.push("");

if (suppliers.length) {
  lines.push("-- Supplier");
  for (const r of suppliers) {
    lines.push(
      `INSERT INTO "Supplier" (id, name, "createdAt") VALUES (${sqlString(r.id)}, ${sqlString(r.name)}, ${sqlTimestamp(r.createdAt)}) ON CONFLICT (id) DO NOTHING;`
    );
  }
  lines.push("");
}

if (products.length) {
  lines.push("-- Product");
  for (const r of products) {
    lines.push(
      `INSERT INTO "Product" (id, name, "skuFwn", "createdAt") VALUES (${sqlString(r.id)}, ${sqlString(r.name)}, ${sqlString(r.skuFwn)}, ${sqlTimestamp(r.createdAt)}) ON CONFLICT (id) DO NOTHING;`
    );
  }
  lines.push("");
}

if (skus.length) {
  lines.push("-- SupplierSKU");
  for (const r of skus) {
    lines.push(
      `INSERT INTO "SupplierSKU" (id, "productId", sku, brand) VALUES (${sqlString(r.id)}, ${sqlString(r.productId)}, ${sqlString(r.sku)}, ${sqlString(r.brand)}) ON CONFLICT (id) DO NOTHING;`
    );
  }
  lines.push("");
}

lines.push("COMMIT;");
lines.push("");

mkdirSync(dirname(OUT_PATH), { recursive: true });
writeFileSync(OUT_PATH, lines.join("\n"), "utf8");

console.log(`✅ Wrote ${OUT_PATH} (${lines.length} lines)`);
